version: '3'

services:
  api:
    build: api
    environment:
      PORT: 3030
    ports:
      - '3030:3030'
    restart: always

  front:
    build: front
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    links:
      - api
    restart: always
