version: '3.8'

services:
  challenge-front:
    image: node:18.12.0-alpine
    working_dir: /usr/app
    user: node
    restart: always
    volumes:
      - ./:/usr/app
      - ./src:/usr/app/src
    command: sh -c "yarn && yarn dev"
