# FROM node:16-alpine AS build

# WORKDIR /app

# COPY package*.json tsconfig*.json ./
# RUN yarn

# COPY tsconfig.json .
# COPY prisma ./prisma
# COPY src ./src
# RUN yarn prisma generate
# RUN yarn build

# FROM node:16-alpine AS runtime

# WORKDIR /app

# COPY package*.json ./
# COPY --from=build /app/dist ./dist

# COPY prisma ./prisma
# RUN yarn 
# run yarn prisma generate

# EXPOSE 3000

# CMD [ "yarn", "start:prod" ]



FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

RUN yarn

COPY . .

RUN npx prisma generate

RUN yarn build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]