import Head from 'next/head'
import { Banner } from '../components/sections/Banner'
import { Cards } from '../components/sections/Cards'
import { Header } from '../components/sections/Header'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Cards />

    </>
  )
}
