version: '3.7'
services:
  redis:
    image: redis:5.0.5-alpine
    # volumes:
    #   - ./redis.conf /usr/local/etc/redis/redis.conf
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - redisnet
  elasticsearch:
    image: elasticsearch:7.3.1
    environment:
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
  api:
    build:
      context: .
    volumes:
      - .:/var/www/api
    working_dir: /var/www/api
    command: bash -c "npm ci && npm run es:populate && npm run prod"
    environment:
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - CACHE_PREFIX=ct
      - ES_HOST=http://elasticsearch:9200
    networks:
      - web
      - redisnet
      - esnet
    ports:
      - 4000:4000
    links:
      - redis
      - elasticsearch
    depends_on:
      - redis
      - elasticsearch
  webserver:
    image: nginx:1.16.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - serverdata:/var/www/html
    networks:
      - web
    ports:
      - 80:80
    links:
      - api
    depends_on:
      - api

volumes:
  esdata:
    driver: local
  serverdata:
    driver: local

networks:
  web:
  redisnet:
  esnet:
