version: '3.7'
networks:
  web:
services:
  api:
    build:
      context: .
    volumes:
      - .:/var/www/api
    working_dir: /var/www/api
    command: bash -c "npm ci && npm run prod"
    networks:
      - web
    ports:
      - 4000:4000
  webserver:
    image: nginx:1.16.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    ports:
      - 80:80
    links:
      - api
    depends_on:
      - api
